#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd -c ~/.config/bspwm/sxhkdrc &

xsetroot -cursor_name left_ptr &
picom --config ~/.config/bspwm/picom/picom.conf --experimental-backends &
feh --bg-fill ~/.config/bspwm/wallpapers/blossom.png & 
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
dunst -config ~/.config/bspwm/dunst/dunstrc &
~/.config/bspwm/polybar/launch.sh &

bspc monitor -d 1 2 3 4 5

bspc config border_width         0
bspc config border_radius       10
bspc config window_gap          12

bspc config focused_border_color "#89dceb"

bspc config top_padding 70
bspc config bottom_padding 50
bspc config left_padding 30
bspc config right_padding 30
